version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.server
      args:
        env: $NODE_ENV
    ports:
      - "10080:80"
  admin:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.admin
    ports:
      - "10081:80"
    depends_on:
      - api