apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJ3YW50c3RvYmVjaGFrIiwicGFzc3dvcmQiOiIwOTMxMDkxOTE1d3N4IiwiZW1haWwiOiJ3YW50c3RvYmVjaGFrQGdtYWlsLmNvbSIsImF1dGgiOiJkMkZ1ZEhOMGIySmxZMmhoYXpvd09UTXhNRGt4T1RFMWQzTjQifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: docker
  namespace: {{ .Values.environment }}
type: kubernetes.io/dockerconfigjson
