apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:7.5.2
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN
          value: "true"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: "X-ASSIST-WEBAUTH-USER"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 472
