FROM node:14.15.0-alpine

ARG TARGET
ARG ENV_CONFIG
ENV NODE_ENV=production
ENV ENV_CONFIG=$ENV_CONFIG


WORKDIR /app
COPY package.json package-lock.json ./
RUN apk add --no-cache --virtual .gyp \
         python \
         make \
         g++ \
     && npm install \
     && apk del .gyp
RUN npm i
RUN npm i -g pm2

COPY ./src ./src
COPY ./tools ./tools
COPY .* ./
COPY *.* ./
COPY ./build/server ./build/server

EXPOSE 80
CMD ["pm2-runtime", "./build/server/app.js"]
